# Generated by Django 5.1.3 on 2024-12-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameApp', '0002_prize'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
