# Generated by Django 5.1.3 on 2024-12-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameApp', '0004_alter_user_managers_user_date_joined_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
