# Generated by Django 5.1.1 on 2024-09-26 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machine', '0001_initial'),
        ('player', '0001_initial'),
        ('prize', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=100)),
                ('play_time', models.DateTimeField()),
                ('machine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.machine')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.player')),
                ('prize_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prize.prize')),
            ],
        ),
    ]
